config/routes.rb
Rails.application.routes.draw do
  root 'searches#new'

  resources :uploads,   only: [:new, :create]
  resources :searches,  only: [:new]
  resources :speaches,  only: [:edit, :update]
  get '/search' => 'searches#search'

end

app/models/speach.rb
require 'active_support/core_ext/securerandom'

class Speach
  attr_accessor :id, :speaker, :transcript, :filename, :tags, :es_id

  def initialize(attrs = {})
    attrs.each { |k, v| public_send("#{k}=", v) }
    self.id ||= SecureRandom.base58(24)
  end

  def to_hash
    {
      id: id,
      speaker: speaker,
      transcript: transcript,
      filename: filename,
      tags: tags
    }
  end

  def to_param
    id
  end

  def model_name
    'speach'.freeze
  end

  def save
    result = $redis.mapped_hmset(redis_key, to_hash)
    result == 'OK'.freeze
  end

  def self.find(id)
    attrs = $redis.hgetall("speach:#{id}")
    self.new(attrs)
  end

  private

  def redis_key
    "speach:#{id}"
  end
end

app/models/speach_repository.rb
require 'typhoeus/adapters/faraday'

class SpeachRepository
  include Elasticsearch::Persistence::Repository

  client Elasticsearch::Client.new url: '127.0.0.1:9200', log: false

  index :speaches
  type  :speach

  # settings analysis: {
  #   analyzer: {
  #     french_anal: { type: 'snowball', language: 'French', stopwords: '_french_' }
  #   }
  # }

  settings analysis: {
    "filter": {
        "french_elision": {
          "type":         "elision",
          "articles_case": true,
            "articles": [
              "l", "m", "t", "qu", "n", "s",
              "j", "d", "c", "jusqu", "quoiqu",
              "lorsqu", "puisqu"
            ]
        },
        "french_stop": {
          "type":       "stop",
          "stopwords":  "_french_"
        },
        "french_stemmer": {
          "type":       "stemmer",
          "language":   "light_french"
        }
      },
      "analyzer": {
        "custom_french": {
          "tokenizer": "standard",
          "filter": [
            "french_elision",
            "lowercase",
            "asciifolding",
            "french_stop",
            "french_stemmer"
          ]
        }
      }
    }

  mapping do
    indexes :transcript,  type: :string, analyzer: 'custom_french'
    indexes :speaker,     type: :string, index: :not_analyzed
    indexes :filename,    type: :string, index: :not_analyzed
    indexes :tags,        type: :string, index: :not_analyzed
  end

  create_index!

  def serialize(document)
    {
      id: document.id,
      speaker: document.speaker,
      transcript: document.transcript,
      filename: document.filename,
      tags: document.tags.split(/\s+/).map(&:strip)
    }
  end

  def deserialize(document)
    hash = document['_source'.freeze]
    hash['tags'.freeze] = hash['tags'.freeze].join(' ') if hash['tags'.freeze].is_a?(Array)
    Speach.new(hash)
  end
end

app/models/speaker.rb
class Speaker
  NAMES = [
    'Patrick Cohen',
    'Léa Salamé',
    'Nicolas Demoran',
    'Charline Vanhoenacker',
    'Mathieu Vidard'
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def search
    speaker = params.require(:speaker)
    terms   = params[:q]

    query   = {
      query: {
        bool: {
          should: [
            { match: { transcript: terms } },
            { term: { tags: params[:tags].downcase } }
          ]
        }
      },
      filter: {
        term: { speaker: speaker }
      }
    }

    @results = SpeachRepository.search(query, size: 100).to_a
    if @results.empty?
      head :no_content
    else
      render partial: 'result', collection: @results, as: :result
    end
  end
end

app/controllers/speaches_controller.rb
class SpeachesController < ActionController::Base
  layout 'application'

  def edit
    @speach = Speach.find(params[:id])
  end

  def update
    @speach = Speach.find(params[:id])
    @speach.transcript = params[:transcript]
    @speach.save
    SpeachRepository.save(@speach)
    redirect_to root_path, notice: 'Speach updated successfully.'
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
  end

  def create
    @file     = params[:sound]
    @uploader = SpeachUploader.new
    result = @uploader.store!(@file)
    speach = Speach.new(speaker: params[:speaker], filename: @uploader.filename, tags: params[:tags])
    if speach.save
      SpeachToTextWorker.perform_async(speach.id)
      redirect_to new_upload_path, notice: 'File uploaded successfully.'
    else
      redirect_to new_upload_path, notice: 'Something went wrong, my bad.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transcriber</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'aurora' %>
  <%= javascript_include_tag 'flac' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="head">
    <%= link_to "Search", root_path %> | <%= link_to "Upload", new_upload_path %>
  </div>

  <% if flash.key?(:notice) %>
    <div class="notice" style="border-color: 1px solid green">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="content">
      <%= yield %>
  </div>
</body>
</html>

app/views/searches/_result.html.erb
<div class="result" style="border-bottom: 1px solid #000" data-id="<%= result.id %>">
  <div>
    <p>
      <b>File: </b>
      <%= link_to result.filename, "https://storage.googleapis.com/haymakerforever/uploads/#{result.filename}", class: 'file' %>
      <a href="#" class="player play">Play</a>
      <a href="#" class="player pause">Pause</a>
      <span class="icon"></span>
    </p>
    <p><b>Tags: </b><%= result.tags %></p>
    <p><b>Fulltext: </b><%= result.transcript %> <%= link_to 'Edit', edit_speach_path(result) %></p>
  </div>
</div>

app/views/searches/new.html.erb
<div class="search">
  <%= form_tag(search_path, method: :get, remote: true) do %>
    <%= label_tag(:q, 'Search for:') %>
    <%= text_field_tag(:q) %>
    <%= label_tag(:tags, 'Tags') %>
    <%= text_field_tag :tags %>
    <%= label_tag(:speaker, 'Speaker:') %>
    <%= select_tag :speaker, options_for_select(Speaker::NAMES) %>
    <%= submit_tag 'Search' %>
  <% end %>
</div>

<div class="results">
  <%= render 'shared/tags' %>
</div>

app/views/shared/_tags.html.erb
<p>Voici les 7 tags qu’on utilise pour entrer et chercher les sons : </p>
<ul>
  <li>W, pour <b>WTF</b> : Tous ce qui est drôle, amusants, et qui vous semble intéressant a utiliser pour mettre du fun dans nos épisodes sera taguée W</li>
  <li>S, pour <b>Science</b> : Dès qu’on a un extrait un peu scientifique ou des mots qui appartiennent au registre des sciences on tag S.</li>
  <li>R, pour <b>Réaction</b> : On taguera avec R tous ce qui est les réactions courtes, qui permettent de faire vivre les animateurs, les « Oui » « Hmm hmm » « NON » mais aussi des truc du genre « C’est vraiment dingue » etc… mais aussi ce qui est présence genre respirations, soupir etc… il nous en faut aussi.</li>
  <li>Q, pour <b>Questions</b> : Il nous en faudra pleins pour construire l’interview et donc toute phrase qui termine en l’air ou qui est clairement une interrogative sera taguée Q</li>
  <li>P, pour <b>Présentation</b> : la mati!re qu’on va utiliser pour le début de l’épisode et présenter Axel sera taguer P</li>
  <li>C, pour <b>Corps</b> : la matière qui ne rentre pas dans ces quatre premier catégorie sera taguée C</li>
  <li>!, pour les <b>Must-used</b> un son qui vous semble impenssable de ne pas utiliser sera taguer « ! »</li>
</ul>

app/views/speaches/edit.html.erb
<h3>Edit speach</h3>

<div class="">
  <%= form_tag(speach_path(@speach), method: :put) do %>
    <p>
      Tags: <%= @speach.tags %>
    </p>
    <%= label_tag :transcript, 'Transcript' %><br />
    <%= text_area_tag :transcript, @speach.transcript, class: 'edit-transcript' %>
    <p>
      <%= submit_tag 'Update' %>
    </p>
  <% end %>
</div>

app/views/uploads/new.html.erb
<h3>New upload</h3>

<div class="new-upload">
  <%= form_tag(uploads_path, method: :post, multipart: true) do %>
    <%= label_tag :sound, 'Your sound' %>
    <span class="hint">FLAC, mono, 44.1kHz</span>
    <%= file_field_tag :sound %>
    <%= label_tag :speaker, 'Who is speaking?' %>
    <%= select_tag :speaker, options_for_select(Speaker::NAMES) %>
    <%= label_tag :tags, 'Tags' %>
    <%= text_field_tag :tags, nil, placeholder: 'Space separated' %>
    <%= submit_tag 'Upload' %>
  <% end %>
</div>

<div>
  <%= render 'shared/tags' %>
</div>